[project]
name = "docker-nginx-daemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.0",
    "docker>=7.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
